### ISSUE TITLE
Revisar evaluaciones del archivo pizarra_advanced.Rmd

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/introR#13]
Las evaluaciones a las respuestas no están trabajando. Revisar este aspecto en el archivo pizarra_advanced.Rmd

33ix

**Comment by ronnyhdez** [comment]
![error](https://user-images.githubusercontent.com/24282285/95372755-3d83d300-0899-11eb-8ebd-4f01c3a6c561.png)

**Comment by andreavargasmon** [comment]
Parece que es un problema con el dataset que se descarga del bucket, lo digo por el mensaje y porque ya intenté cambiar cosas de evaluación y nada sirve.
