### ISSUE TITLE
Disminuir el tamaño y/o longitud de título del gráfico para evitar solapamiento

### ISSUE THREAD

**Issue by ronnyhdez** [ixpantia/introR#16]
En ejercicio 4 tarea ggplot avanzado

**Comment by ronnyhdez** [comment]
Cambiar la orientación de las etiquetas del eje x de los ejercicios 3 y 4 para que las etiquetas no se solapen.

Mejorar los títulos de los ejes

**Comment by andreavargasmon** [comment]
Creo que este ya debería estar cerrado?

**Comment by mablan** [comment]
Si, así es
