### ISSUE TITLE
Validar si podemos llevar este paquete al CRAN cuando depende de un paquete que no se ha publicado.

### ISSUE THREAD

**Issue by FvD** [ixpantia/introR#59]

**Comment by andreavargasmon** [comment]
[Aqui](https://cran.r-project.org/web/packages/remotes/vignettes/dependencies.html ) dice:

> You can mark any regular dependency defined in the Depends, Imports, Suggests or Enhances fields as being installed from a remote location by adding the remote location to Remotes in your DESCRIPTION file. This will cause remotes to download and install them from the specified location, instead of CRAN.

Por lo que la respuesta es si, si podemos publicar al CRAN aunque `gradethis` no está publicado ahí.
