### ISSUE TITLE
Rhub devuelve error al hacer check

### ISSUE THREAD

**Issue by andreavargasmon** [ixpantia/introR#69]
![Screen Shot 2021-03-03 at 17 20 07](https://user-images.githubusercontent.com/53089319/109885776-bae32200-7c44-11eb-8c93-8aec5afdec92.png)

**Comment by andreavargasmon** [comment]
A su vez, github actions falla en el paso de "Set up R 3.5" o "Set up 3.6". Primero, es extraño que tenga ambas versiones R (asumiendo que eso es) y que estas versiones son tan viejas. Un insight a este error: `cask` es un comando de Mac de [Homebrew ](https://brew.sh/) pero no me queda claro porque sale aqui
![Screen Shot 2021-03-08 at 14 20 13](https://user-images.githubusercontent.com/53089319/110376943-6c090400-8019-11eb-9cc6-2f2c3dc5e7d9.png)

**Comment by andreavargasmon** [comment]
Además, porque estas versiones si la que se incorpora en el DESCRIPTION file es > 4.0.0
![Screen Shot 2021-03-08 at 14 23 27](https://user-images.githubusercontent.com/53089319/110377516-1c770800-801a-11eb-9582-7035af2f4605.png)

**Comment by andreavargasmon** [comment]
Cabe denotar que el R CMD check no tira ningún error 
![Screen Shot 2021-03-08 at 14 00 40](https://user-images.githubusercontent.com/53089319/110378554-5694d980-801b-11eb-821f-7dfa0fd3b572.png)


Y que `devtools::build()` corre sin problema 

![Screen Shot 2021-03-08 at 14 34 59](https://user-images.githubusercontent.com/53089319/110378675-79bf8900-801b-11eb-9a34-a7e9daac360a.png)

**Comment by andreavargasmon** [comment]
`r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3` parece ser de github actions: https://github.com/r-lib/actions#:~:text=GitHub%20Actions%20for%20the%20R%20language,a%20variety%20of%20CI%20tasks.&text=r%2Dlib%2Factions%2Frun,errors%20in%20C%20source%20code. y https://github.com/r-lib/actions/tree/master/setup-r

**Comment by andreavargasmon** [comment]
Lo siquiente aparece durante el check de RHub

![Screen Shot 2021-03-12 at 09 44 40](https://user-images.githubusercontent.com/53089319/110963487-bccd7500-8317-11eb-8983-c532e2b4b521.png)

**Comment by andreavargasmon** [comment]
Pude accesar el `00install.out` de RHub Builder y en efecto dice lo mismo 
![Screen Shot 2021-03-12 at 09 58 47](https://user-images.githubusercontent.com/53089319/110965246-9e687900-8319-11eb-874e-07697a33d23c.png)

**Comment by andreavargasmon** [comment]
En https://github.com/r-hub/rhub/issues/367#issuecomment-621757715 y  https://github.com/r-hub/rhub/issues/374 hay discusiones al respecto y se recomienda hacer lo siguiente: 

```r
rhub::check(
  platform="windows-x86_64-devel",
  env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
)
```
Nota: El autor de esta sugerenncia dice que esto es: "for a package with a bunch of dependencies that need compilation"

En nuestro caso, yo probé:

```r
rhub::check_for_cran(
    platform="windows-x86_64-devel",
     env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"),
     email = "andrea@ixpantia.com"
) 
```
Y al hacerlo no hay error! RHub Builder solo nos devuelve una nota (la que ya conociamos)

![Screen Shot 2021-03-12 at 10 16 43](https://user-images.githubusercontent.com/53089319/110967582-28194600-831c-11eb-855f-e4a731291298.png)

**Comment by FvD** [comment]
Que bueno! a mi me suena como solución. Quizas es porque incluimos un paquete que no esta disponible en el CRAN (y por lo tanto requiere compilacion si o si).
